language: python

python:
    - "3.5"

services:
  - docker

sudo: required

before_install:
    - make travis_up

script:
    - make travis_test

after_success:
    - pip install -U codecov
    - docker exec notes /edx/app/notes/notes/.travis/run_coverage.sh
    - codecov
